import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import Footer from "./ui/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
      {/* Meta */}
      <meta charSet="utf-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta content="Anil z" name="author" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta
        name="description"
        content="Shopwise is Powerful features and You Can Use The Perfect Build this Template For Any eCommerce Website. The template is built for sell Fashion Products, Shoes, Bags, Cosmetics, Clothes, Sunglasses, Furniture, Kids Products, Electronics, Stationery Products and Sporting Goods."
      />
      <meta
        name="keywords"
        content="ecommerce, electronics store, Fashion store, furniture store,  bootstrap 4, clean, minimal, modern, online store, responsive, retail, shopping, ecommerce store"
      />
      {/* SITE TITLE */}
      <title>Shopwise - eCommerce Bootstrap 5 HTML Template</title>
      {/* Favicon Icon */}
      <link
        rel="shortcut icon"
        type="image/x-icon"
        href="./site_assets/images/favicon.png"
      />
      {/* Animation CSS */}
      <link rel="stylesheet" href="./site_assets/css/animate.css" />
      {/* Latest Bootstrap min CSS */}
      <link rel="stylesheet" href="./site_assets/bootstrap/css/bootstrap.min.css" />
      {/* Google Font */}
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&display=swap"
        rel="stylesheet"
      />
      {/* Icon Font CSS */}
      <link rel="stylesheet" href="./site_assets/css/all.min.css" />
      <link rel="stylesheet" href="./site_assets/css/ionicons.min.css" />
      <link rel="stylesheet" href="./site_assets/css/themify-icons.css" />
      <link rel="stylesheet" href="./site_assets/css/linearicons.css" />
      <link rel="stylesheet" href="./site_assets/css/flaticon.css" />
      <link rel="stylesheet" href="./site_assets/css/simple-line-icons.css" />
      {/*- owl carousel CSS*/}
      <link rel="stylesheet" href="./site_assets/owlcarousel/css/owl.carousel.min.css" />
      <link rel="stylesheet" href="./site_assets/owlcarousel/css/owl.theme.css" />
      <link
        rel="stylesheet"
        href="./site_assets/owlcarousel/css/owl.theme.default.min.css"
      />
      {/* Magnific Popup CSS */}
      <link rel="stylesheet" href="./site_assets/css/magnific-popup.css" />
      {/* Slick CSS */}
      <link rel="stylesheet" href="./site_assets/css/slick.css" />
      <link rel="stylesheet" href="./site_assets/css/slick-theme.css" />
      {/* Style CSS */}
      <link rel="stylesheet" href="./site_assets/css/style.css" />
      <link rel="stylesheet" href="./site_assets/css/responsive.css" />
      </head>
      <body>
        {/**HEADER SECTION  */}
        <Header/>
        {/* LOADER */}
        <div className="preloader">
          <div className="lds-ellipsis">
            <span />
            <span />
            <span />
          </div>
        </div>
        {/* END LOADER */}
        {/* Home Popup Section */}
        <div
          className="modal fade subscribe_popup"
          id="onload-popup"
          tabIndex={-1}
          role="dialog"
          aria-hidden="true"
        >
          <div
            className="modal-dialog modal-lg modal-dialog-centered"
            role="document"
          >
            <div className="modal-content">
              <div className="modal-body">
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">
                    <i className="ion-ios-close-empty" />
                  </span>
                </button>
                <div className="row g-0">
                  <div className="col-sm-7">
                    <div className="popup_content  text-start">
                      <div className="popup-text">
                        <div className="heading_s1">
                          <h3>Subscribe Newsletter and Get 25% Discount!</h3>
                        </div>
                        <p>
                          Subscribe to the newsletter to receive updates about new
                          products.
                        </p>
                      </div>
                      <form method="post">
                        <div className="form-group mb-3">
                          <input
                            name="email"
                            required={true}
                            type="email"
                            className="form-control"
                            placeholder="Enter Your Email"
                          />
                        </div>
                        <div className="form-group mb-3">
                          <button
                            className="btn btn-fill-out btn-block text-uppercase"
                            title="Subscribe"
                            type="submit"
                          >
                            Subscribe
                          </button>
                        </div>
                      </form>
                      <div className="chek-form">
                        <div className="custome-checkbox">
                          <input
                            className="form-check-input"
                            type="checkbox"
                            name="checkbox"
                            id="exampleCheckbox3"
                            defaultValue=""
                          />
                          <label
                            className="form-check-label"
                            htmlFor="exampleCheckbox3"
                          >
                            <span>Don't show this popup again!</span>
                          </label>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-sm-5">
                    <div
                      className="background_bg h-100"
                      data-img-src="./site_assets/images/popup_img3.jpg"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* End Screen Load Popup Section */}
        
        {children}
        {/**FOOTER SECTION  */}
        <Footer/>
      </body>

    </html>
  );
}
